title: SathvikPN # name of the site
author: Sathvik PN # name of site's author
email: sathvikapn@gmail.com # email of site's author
url: https://sathvikpn.github.io # root address of the site
baseurl: "" # subpath of the site, e.g. "/blog" (leave it blank "" if you're site shouldn't use a subpath)
description: > # description of the site (multiple lines allowed)
  bit of code, content and character.

permalink: /:slug.html

favicon: "favicon.png" # name+extension of favicon (which must be put on the root folder)
# goat_counter: "yoursitename" # put your GoatCounter name if you want to use GoatCounter analytics

remote_theme: riggraz/no-style-please # if you are using GitHub Pages, change it to remote_theme: riggraz/no-style-please

theme_config:
  appearance: "light" # can be "light", "dark" or "auto"
  back_home_text: "SathvikPN" # customize text for homepage link in post layout
  date_format: "%Y-%m-%d" # customize how date is formatted
  show_description: true # show blog description in home page

social_profiles:
  x: https://x.com/SathvikPN
  

sass:
  style: :compressed

plugins:
  - jekyll-feed
  - jekyll-seo-tag
